name: Build Updater (Vicius)
on:
  pull_request:
    paths:
      - "vicius/**"
      - ".github/workflows/vicius.yml"
  push:
    paths:
      - "vicius/**"
      - ".github/workflows/vicus.yml"
jobs:
  build:
    name: ${{matrix.build-type}}
    env:
      VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install upx
        run: choco install upx
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2
      - name: Make build directory
        run: cmake -E make_directory vicius/build
      - name: Export GitHub Actions cache environment variables
        uses: actions/github-script@v7
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');
      - name: Configure
        working-directory: vicius/build
        id: configure
        run: cmake ..
      - name: Compile
        working-directory: vicius/build
        run: cmake --build . --parallel --config ${{matrix.build-type}} --verbose
      - name: Upload Executable Artifacts
        uses: actions/upload-artifact@v4
        if: ${{ matrix.build-type == 'Release' }}
        with:
          name: "Updater"
          path: vicius/build/Updater-Release.exe
    strategy:
      matrix:
        build-type: [Release, Debug]
